export enum HttpMethod {
  "GET" = "GET",
  "POST" = "POST",
  "PUT" = "PUT",
  "DELETE" = "DELETE",
  "PATCH" = "PATCH",
  "OPTIONS" = "OPTIONS",
  "HEAD" = "HEAD",
  "CONNECT" = "CONNECT",
  "TRACE" = "TRACE",
  "LINK" = "LINK",
  "UNLINK" = "UNLINK",
  "PURGE" = "PURGE",
  "LOCK" = "LOCK",
  "UNLOCK" = "UNLOCK",
  "PROPFIND" = "PROPFIND",
  "VIEW" = "VIEW",
}
